name: "Podcast Generator"
author: "T"
description: "Podcast generator used by many."

runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  name:
    description: The name of the commiter
    required: true
    defaults: "${GITHUB_ACTOR}"
  email:
    description: The email of the commiter
    required: true
    defaults: "${INPUT_EMAIL}"
